name: attendance_app
description: "Attendance App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^13.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_map: ^7.0.2
  flutter_map_location_marker: ^9.1.1
  latlong2: ^0.9.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  fluentui_icons: ^1.0.0
  ionicons: ^0.2.2
  hive_generator: ^2.0.1
  build_runner: ^2.4.12
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

